name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # See https://github.com/actions/checkout/commits
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Prepare pack
        run: bash prepare_pack.sh

      - name: Zip pack
        run: zip GeyserOptionalPack.mcpack -r . -x ".*" required_files.txt prepare_pack.sh

      - name: Archive artifacts
        # See https://github.com/actions/upload-artifact/commits
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: success()
        with:
          name: GeyserOptionalPack
          path: GeyserOptionalPack.mcpack

      - name: Get Version
        if: ${{ success() && github.repository == 'GeyserMC/GeyserOptionalPack' && github.ref_name == 'master' }}
        id: get-version
        run: |
          version=$(cat manifest.json | jq -r '.header.version | join(".")')
          echo "VERSION=${version}" >> $GITHUB_OUTPUT

      - name: Get Release Metadata
        if: ${{ success() && github.repository == 'GeyserMC/GeyserOptionalPack' && github.ref_name == 'master' }}
        uses: GeyserMC/actions/release@master
        id: metadata
        with:
          appID: ${{ secrets.RELEASE_APP_ID }}
          appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
          files: |
            geyseroptionalpack:GeyserOptionalPack.mcpack
          releaseEnabled: false
          saveMetadata: true
          releaseProject: 'geyseroptionalpack'
          releaseVersion: ${{ steps.get-version.outputs.VERSION }}

      - name: Publish to Downloads API
        if: ${{ success() && github.repository == 'GeyserMC/GeyserOptionalPack' && github.ref_name == 'master' }}
        uses: GeyserMC/actions/upload-release@master
        with:
          username: ${{ vars.DOWNLOADS_USERNAME }}
          privateKey: ${{ secrets.DOWNLOADS_PRIVATE_KEY }}
          host: ${{ secrets.DOWNLOADS_SERVER_IP }}
          files: |
            GeyserOptionalPack.mcpack
